### ISSUE TITLE
Hey, need help?

### ISSUE THREAD

**Issue by Epicminer256** [undadasheets35/proxy-alloy-2#1]
I recognized the website cause I made it for school. Want to revive it sometime? Ill be down to help

**Comment by undadasheets35** [comment]
Hey, thank you for wanting to help but I don't have access to it right now

**Comment by Epicminer256** [comment]
Bro I was the original site owner for that specific alloy website, I can recreate it with my spare time

**Comment by Epicminer256** [comment]
All I have to do is boot up a alloy server, change up the UI, and make a bookmarklet client. I had this as part of my bookmarklet toolset I used to host

**Comment by undadasheets35** [comment]
Oh, OK you don't need to do that, but if you really want to go for it

**Comment by Epicminer256** [comment]
Lol will do, Imma link the repl here when I am done.

**Comment by undadasheets35** [comment]
Ok, thanks.

**Comment by Epicminer256** [comment]
https://alloy.rawmeateater.repl.co/

Remade with the original proxy (alloy)

**Comment by Epicminer256** [comment]
Source/project file at https://replit.com/@rawmeateater/alloy

**Comment by undadasheets35** [comment]
Thank you

**Comment by Epicminer256** [comment]
Arighty, done with it. it has built into the site a bookmark script allong with a section to add quick sites. You can clone and edit the site's source to add more quick site buttons and such.

**Comment by undadasheets35** [comment]
Awesome, thanks!

**Comment by undadasheets35** [comment]
Hey, would you want some simple code for an rpg game, it's Javascript so it
pretty easy

**Comment by Epicminer256** [comment]
Like what do you mean, like is like a game you made compleatly? Or does it need to be like polished?

**Comment by undadasheets35** [comment]
It's just a simple code that could use a little work to make better but you
don't have to do anything with it

**Comment by Epicminer256** [comment]
sure, you can make a repository and maybe I may leave a commit on it
